### ISSUE TITLE
Trouble signing in as admin

### ISSUE THREAD

**Issue by jbainbridge98** [QihanLu/CS419#3]
I may not be doing this correctly, but when I type in admin for the name and password, I cannot log in as admin.
![Screenshot (12)](https://user-images.githubusercontent.com/56710599/144734156-e3a9eaa4-fdff-4f45-b3d9-e326de993cd8.png)

**Comment by QihanLu** [comment]
Hi, you should use 
username:Admin
password:admin
to login

**Comment by jbainbridge98** [comment]
> Hi, you should use 
> username:Admin
> password:admin
> to login

Ah alright

**Comment by symxmyz233** [comment]
You can close this issue, beacuse it is not counted as a bug.
